### ISSUE TITLE
support gpu acceleration on multiple platforms

### ISSUE THREAD

**Issue by cameronraysmith** [pinellolab/pyrovelocity#6]
To support GPU utilization on Apple M1 or M2 ( https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/ ) pyrovelocity would need to support pytorch `>=1.12`​. For reference the latest stable version is ​`1.12.1​`.

The library currently supports ​`1.8.*​`. 

With, for example, the following channels ([note ​`nodefaults​`](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html?highlight=nodefaults#creating-an-environment-file-manually), which helps to avoid confusion of dependency versions between conda-forge and anaconda package repositories)

```yml
channels:
- conda-forge
- bioconda
- nodefaults
```

and inclusion of dependency on

```yml
  - pytorch=1.8.*
```

in the default environment configuration file, then when `  - pytorch>=​1.12` (at upgrade from current dependencies across the `1.12` threshold), GPU acceleration should work by default on the M1/2.

Relative to the above dependency in the package `environment.yml`, 

<details>
<summary>environment.yml</summary>

```yaml
name: pyrovelocity

channels:
  - conda-forge
  - bioconda
  # https://stackoverflow.com/a/71110028/446907
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults

dependencies:
  - python=3.8
  - mamba=0.27.0
  - conda-lock=1.1.3
  - leidenalg=0.9.0
  - pyro-ppl=1.6.0
  - pip=22.2.2
  - seaborn=0.11.2
  - scvelo=0.2.4
  - scvi-tools=0.13.0
  - pytorch-lightning=1.3.0
#  - pytorch-gpu=1.8.*
#  - pytorch=1.8.*=*cuda*
  - pytorch=1.8.*
  - scikit-misc=0.1.4
  - torchmetrics=0.5.1
  - h5py=3.7.0
  - anndata=0.7.5
  - adjusttext=0.7.3
  - astropy=5.1
  - pip:
    - cospar==0.2.1
```

</details>

including a note such as the following

```markdown
To enable GPU acceleration on linux platforms, you may attempt to execute a command similar to

conda install -y pytorch-gpu=1.8.* -c conda-forge

if your environment is compatible, for example, with 
[conda virtual package](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html) 
`__cuda >= 11`. 

Note that the `pytorch-gpu` package pointer only works on linux platforms. 
An alternative is to specify constraints such as `pytorch=1.8.*=*cuda*`. 
Please see information regarding associated dependencies in

- [conda-forge/pytorch-gpu:1.8.0](https://anaconda.org/conda-forge/pytorch-gpu/files?version=1.8.0) 
- [conda-forge/cudatoolkit:11.2.2](https://anaconda.org/conda-forge/cudatoolkit/files?version=11.2.2)
- [nvidia cuda toolkit <--> driver version compatibility](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions__table-cuda-toolkit-driver-versions)
```

should allow anyone to enable GPU acceleration on linux platforms. See references to one dependency chain from [pytorch-gpu](https://anaconda.org/conda-forge/pytorch-gpu/files?version=1.8.0) to [cudatoolkit](https://anaconda.org/conda-forge/cudatoolkit/files?version=11.2.2) below.
